<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msg_1.CollectConfigBackupDevicesResponse</code>
 */
class CollectConfigBackupDevicesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .msg_1.CollectConfigBackupDevicesResponse.DeviceBackupStatus device_statuses = 1;</code>
     */
    private $device_statuses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Msg_1\CollectConfigBackupDevicesResponse\DeviceBackupStatus[]|\Google\Protobuf\Internal\RepeatedField $device_statuses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .msg_1.CollectConfigBackupDevicesResponse.DeviceBackupStatus device_statuses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeviceStatuses()
    {
        return $this->device_statuses;
    }

    /**
     * Generated from protobuf field <code>repeated .msg_1.CollectConfigBackupDevicesResponse.DeviceBackupStatus device_statuses = 1;</code>
     * @param \Msg_1\CollectConfigBackupDevicesResponse\DeviceBackupStatus[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeviceStatuses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msg_1\CollectConfigBackupDevicesResponse\DeviceBackupStatus::class);
        $this->device_statuses = $arr;

        return $this;
    }

}

