<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

if (false) {
    /**
     * This class is deprecated. Use Msg_1\CollectConfigBackupDevicesResponse\DeviceBackupStatus instead.
     * @deprecated
     */
    class CollectConfigBackupDevicesResponse_DeviceBackupStatus {}
}
class_exists(CollectConfigBackupDevicesResponse\DeviceBackupStatus::class);
@trigger_error('Msg_1\CollectConfigBackupDevicesResponse_DeviceBackupStatus is deprecated and will be removed in the next major release. Use Msg_1\CollectConfigBackupDevicesResponse\DeviceBackupStatus instead', E_USER_DEPRECATED);

