<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

/**
 * Protobuf type <code>msg_1.DestinationOption</code>
 */
class DestinationOption
{
    /**
     * Used for broadcast messages, applicable for Notifications only
     *
     * Generated from protobuf enum <code>TO_ALL = 0;</code>
     */
    const TO_ALL = 0;
    /**
     * Used for single destination messages only, generates AMBIGUOUS_DESTINATION_ERROR error
     * in case of multiple registered destinations with same ServiceType 
     *
     * Generated from protobuf enum <code>TO_ONE = 1;</code>
     */
    const TO_ONE = 1;
}

