<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

/**
 * Protobuf type <code>msg_1.ErrorCode</code>
 */
class ErrorCode
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_ERROR = 0;</code>
     */
    const UNKNOWN_ERROR = 0;
    /**
     * Generated from protobuf enum <code>MESSAGE_SOURCE_NOT_REGISTERED_ERROR = 1;</code>
     */
    const MESSAGE_SOURCE_NOT_REGISTERED_ERROR = 1;
    /**
     * Generated from protobuf enum <code>DESTINATION_NOT_REGISTERED_ERROR = 2;</code>
     */
    const DESTINATION_NOT_REGISTERED_ERROR = 2;
    /**
     * Generated from protobuf enum <code>AMBIGUOUS_DESTINATION_ERROR = 3;</code>
     */
    const AMBIGUOUS_DESTINATION_ERROR = 3;
    /**
     * Generated from protobuf enum <code>NOT_IMPLEMENTED_ERROR = 4;</code>
     */
    const NOT_IMPLEMENTED_ERROR = 4;
    /**
     * Generated from protobuf enum <code>MALFORMED_MESSAGE_ERROR = 5;</code>
     */
    const MALFORMED_MESSAGE_ERROR = 5;
}

