<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msg_1.GetDownInterfacesResponse</code>
 */
class GetDownInterfacesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_ready = 1;</code>
     */
    private $is_ready = false;
    /**
     * Generated from protobuf field <code>repeated .msg_1.Interface interfaces = 2;</code>
     */
    private $interfaces;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_ready
     *     @type \Msg_1\PBInterface[]|\Google\Protobuf\Internal\RepeatedField $interfaces
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_ready = 1;</code>
     * @return bool
     */
    public function getIsReady()
    {
        return $this->is_ready;
    }

    /**
     * Generated from protobuf field <code>bool is_ready = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReady($var)
    {
        GPBUtil::checkBool($var);
        $this->is_ready = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .msg_1.Interface interfaces = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInterfaces()
    {
        return $this->interfaces;
    }

    /**
     * Generated from protobuf field <code>repeated .msg_1.Interface interfaces = 2;</code>
     * @param \Msg_1\PBInterface[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInterfaces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Msg_1\PBInterface::class);
        $this->interfaces = $arr;

        return $this;
    }

}

