<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msg_1.MessageSource</code>
 */
class MessageSource extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msg_1.ServiceType service = 1;</code>
     */
    private $service = 0;
    /**
     * 1. Shall be filled with id received in RegisterMessageSourceResponse message
     * 2. Shall be filled with 0 for RegisterMessageSourceRequest message
     *
     * Generated from protobuf field <code>uint32 id = 2;</code>
     */
    private $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $service
     *     @type int $id
     *           1. Shall be filled with id received in RegisterMessageSourceResponse message
     *           2. Shall be filled with 0 for RegisterMessageSourceRequest message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.msg_1.ServiceType service = 1;</code>
     * @return int
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>.msg_1.ServiceType service = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkEnum($var, \Msg_1\ServiceType::class);
        $this->service = $var;

        return $this;
    }

    /**
     * 1. Shall be filled with id received in RegisterMessageSourceResponse message
     * 2. Shall be filled with 0 for RegisterMessageSourceRequest message
     *
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 1. Shall be filled with id received in RegisterMessageSourceResponse message
     * 2. Shall be filled with 0 for RegisterMessageSourceRequest message
     *
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

}

