<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * General message structure sent from Source to Destination over network.
 *
 * Generated from protobuf message <code>msg_1.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique id of the message (valuable for Requests only to generate Response message with same id).
     *
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Source of the message.
     *
     * Generated from protobuf field <code>.msg_1.MessageSource src = 2;</code>
     */
    private $src = null;
    /**
     * Destination of the message.
     *
     * Generated from protobuf field <code>.msg_1.MessageDestination dst = 3;</code>
     */
    private $dst = null;
    protected $message_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           Unique id of the message (valuable for Requests only to generate Response message with same id).
     *     @type \Msg_1\MessageSource $src
     *           Source of the message.
     *     @type \Msg_1\MessageDestination $dst
     *           Destination of the message.
     *     @type \Msg_1\ErrorResponse $error_response
     *     @type \Msg_1\RegisterMessageSourceRequest $register_message_source_request
     *     @type \Msg_1\RegisterMessageSourceResponse $register_message_source_response
     *     @type \Msg_1\GetDownDevicesRequest $down_devices_request
     *     @type \Msg_1\GetDownDevicesResponse $down_devices_response
     *     @type \Msg_1\GetDownInterfacesRequest $down_interfaces_request
     *     @type \Msg_1\GetDownInterfacesResponse $down_interfaces_response
     *     @type \Msg_1\GetDownIpv4MonitorsRequest $down_ipv4_monitors_request
     *     @type \Msg_1\GetDownIpv4MonitorsResponse $down_ipv4_monitors_response
     *     @type \Msg_1\GetDownAwsInstancesRequest $down_aws_instances_request
     *     @type \Msg_1\GetDownAwsInstancesResponse $down_aws_instances_response
     *     @type \Msg_1\GetDownWmiServersRequest $down_wmi_servers_request
     *     @type \Msg_1\GetDownWmiServersResponse $down_wmi_servers_response
     *     @type \Msg_1\CollectConfigBackupDevicesRequest $backup_devices_request
     *     @type \Msg_1\CollectConfigBackupDevicesResponse $backup_devices_response
     *     @type \Msg_1\EmailNotification $email_notification
     *     @type \Msg_1\SmsNotification $sms_notification
     *     @type \Msg_1\ServiceStatusNotification $service_status_notification
     *     @type \Msg_1\DefaultGatewayStatusNotification $default_gateway_status_notification
     *     @type \Msg_1\DeviceStatusNotification $device_status_notification
     *     @type \Msg_1\InterfaceStatusNotification $interface_status_notification
     *     @type \Msg_1\Ipv4MonitorStatusNotification $ipv4_monitor_status_notification
     *     @type \Msg_1\AwsInstanceStatusNotification $aws_instance_status_notification
     *     @type \Msg_1\WmiServerStatusNotification $wmi_server_status_notification
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique id of the message (valuable for Requests only to generate Response message with same id).
     *
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Unique id of the message (valuable for Requests only to generate Response message with same id).
     *
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Source of the message.
     *
     * Generated from protobuf field <code>.msg_1.MessageSource src = 2;</code>
     * @return \Msg_1\MessageSource
     */
    public function getSrc()
    {
        return $this->src;
    }

    /**
     * Source of the message.
     *
     * Generated from protobuf field <code>.msg_1.MessageSource src = 2;</code>
     * @param \Msg_1\MessageSource $var
     * @return $this
     */
    public function setSrc($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\MessageSource::class);
        $this->src = $var;

        return $this;
    }

    /**
     * Destination of the message.
     *
     * Generated from protobuf field <code>.msg_1.MessageDestination dst = 3;</code>
     * @return \Msg_1\MessageDestination
     */
    public function getDst()
    {
        return $this->dst;
    }

    /**
     * Destination of the message.
     *
     * Generated from protobuf field <code>.msg_1.MessageDestination dst = 3;</code>
     * @param \Msg_1\MessageDestination $var
     * @return $this
     */
    public function setDst($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\MessageDestination::class);
        $this->dst = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.ErrorResponse error_response = 5;</code>
     * @return \Msg_1\ErrorResponse
     */
    public function getErrorResponse()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.msg_1.ErrorResponse error_response = 5;</code>
     * @param \Msg_1\ErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\ErrorResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.RegisterMessageSourceRequest register_message_source_request = 10;</code>
     * @return \Msg_1\RegisterMessageSourceRequest
     */
    public function getRegisterMessageSourceRequest()
    {
        return $this->readOneof(10);
    }

    /**
     * Generated from protobuf field <code>.msg_1.RegisterMessageSourceRequest register_message_source_request = 10;</code>
     * @param \Msg_1\RegisterMessageSourceRequest $var
     * @return $this
     */
    public function setRegisterMessageSourceRequest($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\RegisterMessageSourceRequest::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.RegisterMessageSourceResponse register_message_source_response = 11;</code>
     * @return \Msg_1\RegisterMessageSourceResponse
     */
    public function getRegisterMessageSourceResponse()
    {
        return $this->readOneof(11);
    }

    /**
     * Generated from protobuf field <code>.msg_1.RegisterMessageSourceResponse register_message_source_response = 11;</code>
     * @param \Msg_1\RegisterMessageSourceResponse $var
     * @return $this
     */
    public function setRegisterMessageSourceResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\RegisterMessageSourceResponse::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownDevicesRequest down_devices_request = 12;</code>
     * @return \Msg_1\GetDownDevicesRequest
     */
    public function getDownDevicesRequest()
    {
        return $this->readOneof(12);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownDevicesRequest down_devices_request = 12;</code>
     * @param \Msg_1\GetDownDevicesRequest $var
     * @return $this
     */
    public function setDownDevicesRequest($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownDevicesRequest::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownDevicesResponse down_devices_response = 13;</code>
     * @return \Msg_1\GetDownDevicesResponse
     */
    public function getDownDevicesResponse()
    {
        return $this->readOneof(13);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownDevicesResponse down_devices_response = 13;</code>
     * @param \Msg_1\GetDownDevicesResponse $var
     * @return $this
     */
    public function setDownDevicesResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownDevicesResponse::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownInterfacesRequest down_interfaces_request = 14;</code>
     * @return \Msg_1\GetDownInterfacesRequest
     */
    public function getDownInterfacesRequest()
    {
        return $this->readOneof(14);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownInterfacesRequest down_interfaces_request = 14;</code>
     * @param \Msg_1\GetDownInterfacesRequest $var
     * @return $this
     */
    public function setDownInterfacesRequest($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownInterfacesRequest::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownInterfacesResponse down_interfaces_response = 15;</code>
     * @return \Msg_1\GetDownInterfacesResponse
     */
    public function getDownInterfacesResponse()
    {
        return $this->readOneof(15);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownInterfacesResponse down_interfaces_response = 15;</code>
     * @param \Msg_1\GetDownInterfacesResponse $var
     * @return $this
     */
    public function setDownInterfacesResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownInterfacesResponse::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownIpv4MonitorsRequest down_ipv4_monitors_request = 16;</code>
     * @return \Msg_1\GetDownIpv4MonitorsRequest
     */
    public function getDownIpv4MonitorsRequest()
    {
        return $this->readOneof(16);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownIpv4MonitorsRequest down_ipv4_monitors_request = 16;</code>
     * @param \Msg_1\GetDownIpv4MonitorsRequest $var
     * @return $this
     */
    public function setDownIpv4MonitorsRequest($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownIpv4MonitorsRequest::class);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownIpv4MonitorsResponse down_ipv4_monitors_response = 17;</code>
     * @return \Msg_1\GetDownIpv4MonitorsResponse
     */
    public function getDownIpv4MonitorsResponse()
    {
        return $this->readOneof(17);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownIpv4MonitorsResponse down_ipv4_monitors_response = 17;</code>
     * @param \Msg_1\GetDownIpv4MonitorsResponse $var
     * @return $this
     */
    public function setDownIpv4MonitorsResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownIpv4MonitorsResponse::class);
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownAwsInstancesRequest down_aws_instances_request = 18;</code>
     * @return \Msg_1\GetDownAwsInstancesRequest
     */
    public function getDownAwsInstancesRequest()
    {
        return $this->readOneof(18);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownAwsInstancesRequest down_aws_instances_request = 18;</code>
     * @param \Msg_1\GetDownAwsInstancesRequest $var
     * @return $this
     */
    public function setDownAwsInstancesRequest($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownAwsInstancesRequest::class);
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownAwsInstancesResponse down_aws_instances_response = 19;</code>
     * @return \Msg_1\GetDownAwsInstancesResponse
     */
    public function getDownAwsInstancesResponse()
    {
        return $this->readOneof(19);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownAwsInstancesResponse down_aws_instances_response = 19;</code>
     * @param \Msg_1\GetDownAwsInstancesResponse $var
     * @return $this
     */
    public function setDownAwsInstancesResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownAwsInstancesResponse::class);
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownWmiServersRequest down_wmi_servers_request = 20;</code>
     * @return \Msg_1\GetDownWmiServersRequest
     */
    public function getDownWmiServersRequest()
    {
        return $this->readOneof(20);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownWmiServersRequest down_wmi_servers_request = 20;</code>
     * @param \Msg_1\GetDownWmiServersRequest $var
     * @return $this
     */
    public function setDownWmiServersRequest($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownWmiServersRequest::class);
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownWmiServersResponse down_wmi_servers_response = 21;</code>
     * @return \Msg_1\GetDownWmiServersResponse
     */
    public function getDownWmiServersResponse()
    {
        return $this->readOneof(21);
    }

    /**
     * Generated from protobuf field <code>.msg_1.GetDownWmiServersResponse down_wmi_servers_response = 21;</code>
     * @param \Msg_1\GetDownWmiServersResponse $var
     * @return $this
     */
    public function setDownWmiServersResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\GetDownWmiServersResponse::class);
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.CollectConfigBackupDevicesRequest backup_devices_request = 22;</code>
     * @return \Msg_1\CollectConfigBackupDevicesRequest
     */
    public function getBackupDevicesRequest()
    {
        return $this->readOneof(22);
    }

    /**
     * Generated from protobuf field <code>.msg_1.CollectConfigBackupDevicesRequest backup_devices_request = 22;</code>
     * @param \Msg_1\CollectConfigBackupDevicesRequest $var
     * @return $this
     */
    public function setBackupDevicesRequest($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\CollectConfigBackupDevicesRequest::class);
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.CollectConfigBackupDevicesResponse backup_devices_response = 23;</code>
     * @return \Msg_1\CollectConfigBackupDevicesResponse
     */
    public function getBackupDevicesResponse()
    {
        return $this->readOneof(23);
    }

    /**
     * Generated from protobuf field <code>.msg_1.CollectConfigBackupDevicesResponse backup_devices_response = 23;</code>
     * @param \Msg_1\CollectConfigBackupDevicesResponse $var
     * @return $this
     */
    public function setBackupDevicesResponse($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\CollectConfigBackupDevicesResponse::class);
        $this->writeOneof(23, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.EmailNotification email_notification = 100;</code>
     * @return \Msg_1\EmailNotification
     */
    public function getEmailNotification()
    {
        return $this->readOneof(100);
    }

    /**
     * Generated from protobuf field <code>.msg_1.EmailNotification email_notification = 100;</code>
     * @param \Msg_1\EmailNotification $var
     * @return $this
     */
    public function setEmailNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\EmailNotification::class);
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.SmsNotification sms_notification = 101;</code>
     * @return \Msg_1\SmsNotification
     */
    public function getSmsNotification()
    {
        return $this->readOneof(101);
    }

    /**
     * Generated from protobuf field <code>.msg_1.SmsNotification sms_notification = 101;</code>
     * @param \Msg_1\SmsNotification $var
     * @return $this
     */
    public function setSmsNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\SmsNotification::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.ServiceStatusNotification service_status_notification = 102;</code>
     * @return \Msg_1\ServiceStatusNotification
     */
    public function getServiceStatusNotification()
    {
        return $this->readOneof(102);
    }

    /**
     * Generated from protobuf field <code>.msg_1.ServiceStatusNotification service_status_notification = 102;</code>
     * @param \Msg_1\ServiceStatusNotification $var
     * @return $this
     */
    public function setServiceStatusNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\ServiceStatusNotification::class);
        $this->writeOneof(102, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.DefaultGatewayStatusNotification default_gateway_status_notification = 110;</code>
     * @return \Msg_1\DefaultGatewayStatusNotification
     */
    public function getDefaultGatewayStatusNotification()
    {
        return $this->readOneof(110);
    }

    /**
     * Generated from protobuf field <code>.msg_1.DefaultGatewayStatusNotification default_gateway_status_notification = 110;</code>
     * @param \Msg_1\DefaultGatewayStatusNotification $var
     * @return $this
     */
    public function setDefaultGatewayStatusNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\DefaultGatewayStatusNotification::class);
        $this->writeOneof(110, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.DeviceStatusNotification device_status_notification = 111;</code>
     * @return \Msg_1\DeviceStatusNotification
     */
    public function getDeviceStatusNotification()
    {
        return $this->readOneof(111);
    }

    /**
     * Generated from protobuf field <code>.msg_1.DeviceStatusNotification device_status_notification = 111;</code>
     * @param \Msg_1\DeviceStatusNotification $var
     * @return $this
     */
    public function setDeviceStatusNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\DeviceStatusNotification::class);
        $this->writeOneof(111, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.InterfaceStatusNotification interface_status_notification = 112;</code>
     * @return \Msg_1\InterfaceStatusNotification
     */
    public function getInterfaceStatusNotification()
    {
        return $this->readOneof(112);
    }

    /**
     * Generated from protobuf field <code>.msg_1.InterfaceStatusNotification interface_status_notification = 112;</code>
     * @param \Msg_1\InterfaceStatusNotification $var
     * @return $this
     */
    public function setInterfaceStatusNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\InterfaceStatusNotification::class);
        $this->writeOneof(112, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.Ipv4MonitorStatusNotification ipv4_monitor_status_notification = 113;</code>
     * @return \Msg_1\Ipv4MonitorStatusNotification
     */
    public function getIpv4MonitorStatusNotification()
    {
        return $this->readOneof(113);
    }

    /**
     * Generated from protobuf field <code>.msg_1.Ipv4MonitorStatusNotification ipv4_monitor_status_notification = 113;</code>
     * @param \Msg_1\Ipv4MonitorStatusNotification $var
     * @return $this
     */
    public function setIpv4MonitorStatusNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\Ipv4MonitorStatusNotification::class);
        $this->writeOneof(113, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.AwsInstanceStatusNotification aws_instance_status_notification = 114;</code>
     * @return \Msg_1\AwsInstanceStatusNotification
     */
    public function getAwsInstanceStatusNotification()
    {
        return $this->readOneof(114);
    }

    /**
     * Generated from protobuf field <code>.msg_1.AwsInstanceStatusNotification aws_instance_status_notification = 114;</code>
     * @param \Msg_1\AwsInstanceStatusNotification $var
     * @return $this
     */
    public function setAwsInstanceStatusNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\AwsInstanceStatusNotification::class);
        $this->writeOneof(114, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.msg_1.WmiServerStatusNotification wmi_server_status_notification = 115;</code>
     * @return \Msg_1\WmiServerStatusNotification
     */
    public function getWmiServerStatusNotification()
    {
        return $this->readOneof(115);
    }

    /**
     * Generated from protobuf field <code>.msg_1.WmiServerStatusNotification wmi_server_status_notification = 115;</code>
     * @param \Msg_1\WmiServerStatusNotification $var
     * @return $this
     */
    public function setWmiServerStatusNotification($var)
    {
        GPBUtil::checkMessage($var, \Msg_1\WmiServerStatusNotification::class);
        $this->writeOneof(115, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessageOneof()
    {
        return $this->whichOneof("message_oneof");
    }

}

