<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msg_1.MessageDestination</code>
 */
class MessageDestination extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.msg_1.ServiceType service = 1;</code>
     */
    private $service = 0;
    protected $option_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $service
     *     @type int $id
     *           Responses shall only use it, it is taken from Message.MessageSource.id of the corresponding Request
     *     @type int $option
     *           Requests and Notifications shall use this option
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.msg_1.ServiceType service = 1;</code>
     * @return int
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>.msg_1.ServiceType service = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkEnum($var, \Msg_1\ServiceType::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Responses shall only use it, it is taken from Message.MessageSource.id of the corresponding Request
     *
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->readOneof(2);
    }

    /**
     * Responses shall only use it, it is taken from Message.MessageSource.id of the corresponding Request
     *
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Requests and Notifications shall use this option
     *
     * Generated from protobuf field <code>.msg_1.DestinationOption option = 3;</code>
     * @return int
     */
    public function getOption()
    {
        return $this->readOneof(3);
    }

    /**
     * Requests and Notifications shall use this option
     *
     * Generated from protobuf field <code>.msg_1.DestinationOption option = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOption($var)
    {
        GPBUtil::checkEnum($var, \Msg_1\DestinationOption::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOptionOneof()
    {
        return $this->whichOneof("option_oneof");
    }

}

