<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47;///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 * / COMMON STRUCTURES
 *
 * Generated from protobuf message <code>msg_1.Interface</code>
 */
class PBInterface extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 dev = 1;</code>
     */
    private $dev = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 itf = 2;</code>
     */
    private $itf;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $dev
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $itf
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 dev = 1;</code>
     * @return int|string
     */
    public function getDev()
    {
        return $this->dev;
    }

    /**
     * Generated from protobuf field <code>uint64 dev = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDev($var)
    {
        GPBUtil::checkUint64($var);
        $this->dev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 itf = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItf()
    {
        return $this->itf;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 itf = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItf($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->itf = $arr;

        return $this;
    }

}

