<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>msg_1.RegisterMessageSourceResponse</code>
 */
class RegisterMessageSourceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 destination_id = 1;</code>
     */
    private $destination_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $destination_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 destination_id = 1;</code>
     * @return int
     */
    public function getDestinationId()
    {
        return $this->destination_id;
    }

    /**
     * Generated from protobuf field <code>uint32 destination_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDestinationId($var)
    {
        GPBUtil::checkUint32($var);
        $this->destination_id = $var;

        return $this;
    }

}

