<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Special request to register ability to receive requests and notifications from other services. 
 * Shall be sent to MessageBroker only!
 * Registered Service type shall be taken from MessageSource field of the Message
 *
 * Generated from protobuf message <code>msg_1.RegisterMessageSourceRequest</code>
 */
class RegisterMessageSourceRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Messenger3::initOnce();
        parent::__construct($data);
    }

}

