<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messenger3.proto

namespace Msg_1;

/**
 * Protobuf type <code>msg_1.ServiceType</code>
 */
class ServiceType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_SERVICE = 0;</code>
     */
    const UNKNOWN_SERVICE = 0;
    /**
     * Generated from protobuf enum <code>MESSAGE_BROKER = 1;</code>
     */
    const MESSAGE_BROKER = 1;
    /**
     * Generated from protobuf enum <code>DISCOVERY = 2;</code>
     */
    const DISCOVERY = 2;
    /**
     * Generated from protobuf enum <code>SNMP_MONITORING = 3;</code>
     */
    const SNMP_MONITORING = 3;
    /**
     * Generated from protobuf enum <code>ICMP_MONITORING = 4;</code>
     */
    const ICMP_MONITORING = 4;
    /**
     * Generated from protobuf enum <code>NETFLOW_MONITORING = 5;</code>
     */
    const NETFLOW_MONITORING = 5;
    /**
     * Generated from protobuf enum <code>SYSLOG_MONITORING = 6;</code>
     */
    const SYSLOG_MONITORING = 6;
    /**
     * Generated from protobuf enum <code>AWS_MONITORING = 7;</code>
     */
    const AWS_MONITORING = 7;
    /**
     * Generated from protobuf enum <code>WMI_MONITORING = 8;</code>
     */
    const WMI_MONITORING = 8;
    /**
     * Generated from protobuf enum <code>HTTP_MONITORING = 9;</code>
     */
    const HTTP_MONITORING = 9;
    /**
     * Generated from protobuf enum <code>MSSQL_MONITORING = 10;</code>
     */
    const MSSQL_MONITORING = 10;
    /**
     * Generated from protobuf enum <code>CONFIG_BACKUP = 11;</code>
     */
    const CONFIG_BACKUP = 11;
    /**
     * Generated from protobuf enum <code>MESSENGER = 12;</code>
     */
    const MESSENGER = 12;
    /**
     * Generated from protobuf enum <code>WEB_CLIENT = 13;</code>
     */
    const WEB_CLIENT = 13;
    /**
     * Generated from protobuf enum <code>WEB_SERVER = 14;</code>
     */
    const WEB_SERVER = 14;
}

